version: "3.7"

services:
  keycloak:
    container_name: keycloak_app
    image: jboss/keycloak
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - "/etc/ssl/keycloak/:/etc/x509/https" # map certificates to container
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_HOSTNAME: ${KEYCLOAK_URL}
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
